apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("jaeger.staging.mchill.duckdns.org")
      kind: Rule
      services:
        - name: jaeger-query
          port: 80
