provisionDataStore:
  cassandra: false
  elasticsearch: true
storage:
  type: elasticsearch
elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  extraEnvs:
    - name: ES_JAVA_OPTS
      value: -Xms512m -Xmx512m
  persistence:
    enabled: false
  extraVolumes:
    - name: server2
      persistentVolumeClaim:
        claimName: server2
  extraVolumeMounts:
    - name: server2
      mountPath: /usr/share/elasticsearch/data
      subPath: elasticsearch
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
