apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: server
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgB88WJ4CziM6wqenbTKssDQvUdJYvlEJ+JKk2KCX078fV2U84I04HPDxKGjoNCwZypKkxnwyvJfgGIwE5SqVgIpUHnBeodl2zsceiBXciwGObyh17VZIORXseV9CwpJxXfULyYVC/znsn1qsS7llij+j6i7nfm6pnPgszlplWgLRfdRtypAcieBf7wDJgtlgNA4sSx8/f4HnqhnqPIKvAPhI1DH5uyIXsOvLdzyE4DUY4D/c5q7d8OFfacgMYYvVztshnn55xYjM8KwUxrPrQK9rSVmnauUC9j7lx0uvO9HAPtrnRelddDNmeaDkeg+bKe8sZnjvk6F1DBX1IopBB/3ZOdFfL6rntiyYeWHMa51i6+yoOE9UDpW/Rf44lzz6L/Qyp/3NX8jGF+GZkQzzPD/dwoNRfsMUWmqX8LrcrirHt6h15TXLY00qFfoUTtCxXkoPR46eR0butJFSHMInpz34EJBLYa2Ottsr3bZ7H7A0WQ2sRt+F/igi1gzxSG79g1sJLyCkQNsikk+kVVFmU2E74O/omSkdsNXiTASuzkNM2YvtdZ+dB6n5MrdUBOUIrMG4N2bEmiJ4vENb3bJTTugkN5rTekam6gvJNwwnqrq56EETOJJNYwkSRKc9r54sQwW1SypMgSZT9ckK3l21LaSvjYYq2aiOf+Bxvm26y/dA0caYe9BMe3Mpu0HQOFGVaVwocLasA6fK3LZtFVE8Cg1
    GF_SMTP_USER: AgC/Hk3uRjQBPN9dSEX58n4N+CAuJfKyL250bBivUjKDfN1ReC8IfmFnMoqQ6bx74IJFgGsPtJ9/T0uhHUtBvlmR5fgdHAexiymGZoCYYlIm2uJw+gajSt4nURKDDREGs1IDRpbRncoRHKxzUj+RpXaRfLSTZ0nbmzw+Pq5uFVQSCC6SbQx1Iv0X9ngep3MKfOotT8D+yzEKjDcOmlOviGEcgQZagbHytOibFrRsV2+ZnqNFonqAw9ZC1hrt3vTT7tdYrwWvolMetmCX3JhHsdj9JgzWBotoJv5wH5fmA4NAV9XjDZznknNH5hEmHmhFpRsav21XjZilpZqjiC/V6J4WaDrOEcZCo+siRmgGMjYMsn2GKXeCKARLw4XCfEOH2PIqL+0s5tSrb8C3gM6PlpJaIEYYUsXvT9cyK7WR6jmpC5XiEnQhhf8kMYO2xwXHhxa9z5HLxzEWkdCA+5OFQHVahzr+icjK+LLpPmyMaB20BuC/uoeuEBtS7OYn5ZyzS4EMLonsz8lAQJIL0htkhvn8dsfhOB1ZmPq5iTqqxash25OL2Epwjq0rp+B2nDAZeAcYw4Zve2OWSVpQ7eKQ4cDWJligz/P640GLE90imzk/gVEEdRiRw7NZtHoPbVhlaDomN+XIvrbm0qUxmwT+Yc9epYngiRJNZVeWjXHrijjIeY4/Ng+HubTzltkRF8+l8TwMvf/JzXpUlry2aYZFSj5HvLxLP3Z4wg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: server
    type: Opaque

