loki:
  persistence:
    enabled: true
    existingClaim: server
    subPath: loki
grafana:
  enabled: true
  testFramework:
    enabled: false
  persistence:
    enabled: true
    existingClaim: server
    subPath: grafana
  adminPassword: admin
  plugins:
    - devopsprodigy-kubegraf-app
  smtp:
    existingSecret: grafana
    userKey: GF_SMTP_USER
    passwordKey: GF_SMTP_PASSWORD
  env:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_SMTP_ENABLED: "true"
    GF_SMTP_HOST: smtp.gmail.com:587
    GF_SMTP_FROM_ADDRESS: grafana@mchill.io
prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/alertmanager
  server:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/server
    strategy:
      type: Recreate
  pushgateway:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/pushgateway
  extraScrapeConfigs: |
    - job_name: traefik
      static_configs:
        - targets:
          - traefik-internal:9000
