kind: Deployment
apiVersion: apps/v1
metadata:
  name: static
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: static
          image: nginx:1.19.9@sha256:bae781e7f518e0fb02245140c97e6ddc9f5fcf6aecc043dd9d17e33aec81c832
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: media
              mountPath: /usr/share/nginx/html/podcasts
              subPath: Podcasts
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
