kind: Deployment
apiVersion: apps/v1
metadata:
  name: static
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: static
          image: nginx
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: media
              mountPath: /usr/share/nginx/html/podcasts
              subPath: Podcasts
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
