resources:
  - ingress.yaml
  - sealed-secret.yaml
helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    version: v15.1.3
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: server
    valuesFile: values.yaml
