resources:
  - ingress.yaml
  - sealed-secret.yaml
helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: false
    version: 35.2.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: server
    valuesFile: values.yaml
