apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: server
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgAnFrAEiSYyDi/O/tGNUgOe4HJ1GXslqqmkMlqiGRFBNyuZuNzhBFwGy3URcgBbQpJawWv7yyZ9LOk4ssk66C7M/TcfblpfMjMwyJreuLFd5bXHLxpmDUWP7oBmQ3GawUXiiBJRyU8O8Jqe7a0VYJxmtE11IA+mcBYNjbgmDQpqGDe4R1TxupvrX61UGPqggCQ6oPQhaBeHbHZaGej7lzsS6eRpup8foXSezSre4GWA/6UX5cg9dhOtu77hiEN+0TWFzXvufapaCTs8c+QDhacmrQeqdBmPprZcd4RnCQqg9AYnqpkQ2wD+TykOmHMhKPxRYQ1k6rEdWwHIpXXUG7RG9YZRQLhJP0IXoQVblsBNb30qhv/fIULAQC+2APK6JUi6hDgyV6rSPwnXd8zxa0MFQcsLBX8zVofQ6qa8vh4QQyuSs2rV8Aw1Pl4xsyB9jvqmvrojFkaSeM9v0rwy+E51Ki5q1TxtM0bt+6fkutPqwiTC7I7xFUa1oE+d4gwB+fVoetTLL2zbXEWswL/kw1t8q18/hEDNkEr/3ZGOY1cYj+w3e4Dn41l6IRvkzXEqrIuQiA84D+j4b1S+tsbkweu3WD/6ZGkhf/ffUrOKdUZn1dl2NYNtRyvP3RSrLlXH6qXwz2Ivk4JPo/34wkRqfAV0/RyC1ehBnbPSH1kw0UKd3IEBrxIzfwpPf0DyZNExwbc1VGUHVWhM09WZd5NzHZMJ
    GF_SMTP_USER: AgCMM/qF4isE0VduKBxY2FfWuUqp8iGDvzQhY7y35GV4zQMLA3J9Ys2Jl4vfYYqifrA5AdM8b+7YCKWZLRVw6s1fh1gvyo7vPfEU0yreJ+A0oMnY/+EMW+beHj2z8U0bg/O+x+bZY42Q5N306q50jukEMhtFwVAP1WeY0P5EEuojtAIC8lJb5LbmA/R3EqJf+SbNucapUkuLbwwG+/0OPb9goRGFv2BVhtHSnX9fWkI9UJFawtSSqKkdC00VOZ6mYmBR+63ZymJYCEYqz0Ok4h63XSpJYTa7lvvOhJmJfOHn+BYyMExkd6ABH8tTa1Oa1/ypQNbn36R8t44O7BAa87mmDkDhnSkmALBy4suIh5OIsCH24xTtZKoqDw9dTza63zGYwNFTZtQCvr49Gq61MVcnZ913sI0Fdv+TExcYpQZ3YhD++MgqjLV3l0LObR/bTNkK+Dq33YKv9EFKZAWUfRzDyfGOkJj3lMnfMvx79N48QTS842iwCyfnWO8w3ZG+wfHog5wf19vsASCLpV/GR2N/c9QJXU+PSkih4d5B3GD/+vnjpMBwVy32NUGUd8t1jNLeCnFooiKDQy+SRe6AKWGjeOaptjDe31TRE4vcbxEJ28gLE3WAdlZ+YQ9fl21C0DeqIwlcS4UKeXYrQg89jkgdguQaDvNiIPBQ6WxMi2QcZBGisVhrrHJxaPfrwBu70IrS9/t5eyDZoKnrmoV63bwtE1NqtSBkvQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: server
    type: Opaque

