apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: server
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgCCSdcrTCwkPnrsNrglSGFAB2JX756Zjb4o4uK8YMIcqWTDS5OzXDwxvuv2ThbbyoOoLXQrkC6nnccVnlR+oaC6996lLdREcp0gpFw3WTzWg01kSZrGAjcFlHntyDW0kuNUUjI2gVcqMTCNFVZ/a9eBiFzU56krNoHdKczepIJE/LYfc9VKV/6hQsOvDPZouiF19guPYfZBD7fC3iS+lgCEPHbvXPohpqXsiC5Yt4UETL9/k8/kkwWXLGjd4Rc9oeDPhrZMWYALpBxSodCqlDdRTxw1jO9znaIs8dgaz+mE6VWkl5A6zI3mvjHAV/VMyKeUr+9lOFZPuB25P0FNzVPlHvds3JEWI9gBySe4CvWOnUKWgYkY3Z+8Kw3eMD+FAnBjJ16cF6IOxd65cems87BGy7bkzQAoDjrXb+IXVChEKt+EGNqiBXfpiiDaI9EPTk8WfgK1SjjAijqqk7QOFgyZ7NyU2SYSeaW38YgoXOQRZTN0rH4XpfVwGiSE14DBldESYbip351TnwtLe/wkc4b11BRCKIvCB9ue2QysP+kDgoFmhjYQugc12v04fInxkFl4W4JMzgXv1GPjr/uM1Jx09GVT+nS/vytoVsO/pDJGsQOP6HujYnY6Kcpg/2lWB6H+8D6njHGO6nbcI8WeSByaRr9dgnwJjtErBU04UJwZysAp/mYRb4iJMaQd5CD1cCeW0iBfQMKDz8Q0PXPSgfiS
    GF_SMTP_USER: AgBCGIfsi4lrcQTwq/AhNgr0gMymSHYnj5jZSUC/mmBhN1gH6Opag6HgNUAwBQGOpeAKf815QN3ugMtkOG7jBNIGR1YdVY9UiYgM/lTd2RnsZBhxcsbgJFEKFrdElUINUnbcLN1jAIri+WKOdSwQZvsbVR2N15vFs77nDj/dpD5Wla0B/3c91IGsTVhTzWEAuBCcXffXVrFIKH6nlNKddX+rpYcDaREUSAJYC2M6Qm+U0vu3VIAF2nH16nSnSw6ExyS4M0H+gZf1rhOPZR0qWZXRjVT4lZFJTta0U48lj6+Jbdv3GEluZKGC3xUBmHT96YfqkFm1nbBEd//qBLRypLTFa+Mhinj8h/4+yl2fBD679n32iVJ0lGUI/xrB5Y6f1drfnzER4udDzf/Iq0fnwAfbIQCzJdZ62r28MJDPTKc1/7Husc/RJvL+ukwWZLi7MSRdRWsBYbMkfahCvk/xC+A9z9ion5QupOiVMPxjlczN3nL3MLmDDR0evXOnBtU5YaEhHq90gOCGZyub3/WclOrZHqlppQvN3xpPNsh/S4o3uWALs5S0lLLrfQ1wZ+Zwg+PuCul+weCrNXVOB+LuyjynjHlRPCgLyuVwVDrS4VXFh3mRRlAkHdn4XK7KVvL7BVwVPN57g3ev7NYz07m/G6l54zuAsft/B7bRo4VwM8RCZLqE/T+Y0S9fcA35eB8/JS6f0hHW90KGSMNF7SQB+Q/HkOw3K514kg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: server
    type: Opaque

