kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: static
spec:
  template:
    spec:
      containers:
        - name: static
          image: nginx:1.21.3
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: media
              mountPath: /usr/share/nginx/html/podcasts
              subPath: Podcasts
            - name: media
              mountPath: /usr/share/nginx/html/audiobooks
              subPath: Audiobooks
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
