apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: static-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("static.mchill.io")
      kind: Rule
      services:
        - name: static
          port: 80
      middlewares:
        - name: static
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: static-internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("static.mchill.lan")
      kind: Rule
      services:
        - name: static
          port: 80
      middlewares:
        - name: static
