apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgC4atoVoXO9oQMtykP+SsQv1p0mU0GA4842+5ujkStxtvv3b91WAQs+K1Y1eVwAS1lYbJRVX4n3fSQ53BCgpAD74buE7O8KP0OmPsauQcoLTRSFhTiYbqKVd5oTfcQysWUBylUa1ERhVEznKu7WW6FdEn8TsSCc0HCllpH9gIfzei0oQC9LSd1toCol1ZRaNztCSNwHiSHT6wg+sPgITCINmFqgtdwtftyQA9pfWcwJNv6nGSnBD3JvL/4c57N1RPr+ItLWbMFIHU166G3DshU2p+19qoxIM1duFAWRSx4KSq+yoRkY1PBK6wAiADp+2kU+o0P4ggdYTFJWDvKpb5GqSDQIvAWlKD7yZLq2IBmihchg8sn0RULRdokA7T0HkAOfK/olMKnaZJtM8kMmACKscDq++e1jPDC57dQYdxdxpTrnscmuQHEkcTDXyhaxpSx2zKxQnrjioBRbSNxae2cABhm4zGo2e6u6eSn5L9qOrrmqoBwbeRxNq8iEertYs/yFKSHPQIeiWEtyTD+ai1cr7g4CKGKD/oRqbvSfbuQ62jGqTLtLb1oydihFGfrGH8M+FRFRTS2MUMSDm3R4wxnp3oFpqIZU16lTEn82pjEUtXbeA+KRChFEOPPvojSkZyx05PK0zBeNzSIBaCPTwtdRhsBIjj97omjXCN8FAKcxjcqDlKWSLE+eEmw4uxjl7KiCGRwPInFSmGyJv7tsF52WceBq95YeP2aWxJqccREODliWmxzcmRxVPhbqceA=
  template:
    metadata:
      creationTimestamp: null
      name: static
      namespace: server
    type: Opaque

