apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgCwxZun1r/EX4SfJxxSA4fkuT2VAalf3M9hjdERXYNWvTu4BMSNKDK0EUXi3RmpZlRE6BPdkNpHTwTM/8MNrwgQh91kr3plq9LFkf0nqGkxr3TAqYL9ZsG8GGVrYIJxrMHHY46lMLA4FK6OcRUSiS5EjSzX27EI7xC+vgi8/ZWnR/61p4AgORWLhJGHZIjNn84W2xIOBRHIjrHkF5JThWJ6s8kQhJygY87Bt2iOeDlTSB0EwkP0041KnGtNPX0Kl2z7QaPJP6u/zDk3y0rUdkDVsveoTloVqdM4OcU7B3gr+BTFbGp2ZTg0RmLoPxa/mT/f2n18Pejg2W/mwlO0/u8vfXZ/U74M9xDQLPiwk5m/ZJ/787eqMJrHDiyF5wPQI9i7vSqKRoiryK8US/SDh0l158+rfUTtIVfEV9BND8uXBiTep1p7hOZuEqHJyF5xvgMzLXoNhWLSi11fuz14JsOHwFE/UTwixdBs2L1/QCtg2mnUwUn+H844NRp6lGtJOVstWHQyk5YsMbLRcVLTw1SENLn9cWULqpqZf8k/ou8mOXfwoybwJSK7btjZT7ADDw0EBBsNgVXe2pllqcY6TNAdS4ts4KkPb6JqoVGWN8T531MhdOoqBt4d+35uGz1OgfmSWTaI0taVUgAF6xNzQp26RLw1dPM1Czq5efKvVkJaeJZ2mAt5ty4jUs6n7icj6RmEp8BUcLTF3WM0qs21tBchCJJQWyCjU3O2WihSHSnydmQ1LtrNEpm3s5rnPIU=
  template:
    metadata:
      creationTimestamp: null
      name: static
      namespace: server
    type: Opaque

