apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: static
  namespace: server
spec:
  encryptedData:
    users: AgBpLH3HSgyb1/h00fy5Mm7mfcgkKyp6xUArXp4bg0K7dtpgHvhnhtnLv6PR8iOqeDNDV7l8w2G8OQgCuGoOxniMmGgZ7tySruIFkM/ChJUxgFHjSojNGMozMulaKvfEEthMb5qRfVKlviVNhBKjHNMKuRWX1B8AnUMcLKluGosUAFcUNOQyOjoR5wzqHLgET3y65Y6pDyHGYoxSWev5u0hhI97a9bjqSEQ5+NoFs4gCLjjqNHSZJynEZJ2JjW6DELFPWDSD0dKH/+OVMr2RZMhuq95Du94UI/BLQkXLiQOjAF77oUjFBadINrFhLeT3RiJzaW3ix8RDJd5NEStoV/B4PAGG1EAhfF3VnBfQTmoj9THDuvAIxXTkReARsylbRpxJezLWnHjGjkjy2lRqoOuw+zj+xcmxKUZh98J3rVg0DV/wV9JpFGBgVVJfc4R/jbbjeemsIlsnIhnGRCJQcTUMbQ0G+l/iJOz9KChCz6LeNTxzr/4bVNzt+z0Tw0nLfJ37uTlCmmozmIVzPAerwWL7rs87vdIoPKeB2CLdxvgzQCo19kHiNgRGX3VeElfrjFLUcBxye8194beIk81TG3QblnR+qBN/TjNV/XS+NIqBmUwuqN2N85TRE6KG4deYtamTfU8j5dMdaRJRG5JuSG6sl1LqCF3X54ZlgUs5d77pvzwCkaZc5vj9pRqhqmzqatF74A+65off2H+YEasmQaP+DQxUQcMHfB6SKEhSi06GFIuyVOC/O6knCsx4Bus=
  template:
    metadata:
      creationTimestamp: null
      name: static
      namespace: server
    type: Opaque

