kind: Deployment
apiVersion: apps/v1
metadata:
  name: jackett
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: jackett
          image: ghcr.io/linuxserver/jackett:version-v0.17.794@sha256:4ba7520c21c7fa1c9c593485f2e952c7d52a0bfbd3f029c9319b4eb35d1095dd
          ports:
            - name: jackett
              containerPort: 9117
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: jackett
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
