apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("grafana.staging.mchill.duckdns.org")
      kind: Rule
      services:
        - name: loki-grafana
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("prometheus.staging.mchill.duckdns.org")
      kind: Rule
      services:
        - name: loki-prometheus-server
          port: 80
