grafana:
  enabled: true
  testFramework:
    enabled: false
  persistence:
    enabled: true
    existingClaim: server
    subPath: grafana
  adminPassword: admin
  smtp:
    existingSecret: grafana
    userKey: GF_SMTP_USER
    passwordKey: GF_SMTP_PASSWORD
  env:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_SMTP_ENABLED: "true"
    GF_SMTP_HOST: smtp.gmail.com:587
    GF_SMTP_FROM_ADDRESS: grafana@mchill.duckdns.org
prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/alertmanager
  server:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/server
    strategy:
      type: Recreate
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
  pushgateway:
    persistentVolume:
      enabled: true
      existingClaim: server
      subPath: prometheus/pushgateway
  extraScrapeConfigs: |
    - job_name: traefik
      static_configs:
        - targets:
          - traefik-api:8080
