kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:version-3.0.6.1196
          ports:
            - name: sonarr
              containerPort: 8989
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: sonarr
            - name: media
              mountPath: /tv
              subPath: TV
            - name: data
              mountPath: /data
              subPath: transmission
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
