apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("pihole.mchill.io")
      kind: Rule
      services:
        - name: pihole-tcp
          port: 80
      middlewares:
        - name: pihole
