namespace: traefik-internal
resources:
  - ingress.yaml
  - middleware.yaml
  - namespace.yaml
  - sealed-secret.yaml
  - service.yaml
commonLabels:
  app: traefik-internal
helmCharts:
  - name: traefik
    includeCRDs: false
    version: 10.19.5
    repo: https://helm.traefik.io/traefik
    releaseName: traefik-internal
    namespace: traefik-internal
    valuesFile: values.yaml
