apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs
subsets:
  - addresses:
      - ip: 192.168.1.200
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.1.201
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.1.202
    ports:
      - port: 1
