kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server
spec:
  storageClassName: openebs-jiva
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: default
  volumeName: media
