kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server
  namespace: server
spec:
  storageClassName: openebs-jiva
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: default
  volumeName: media
