version: '3.8'

services:
  dashboard:
    build: dashboard
    restart: always
    environment:
      - TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`$URL`)
      - traefik.http.routers.dashboard.middlewares=auth@file
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.services.dashboard.loadbalancer.server.port=80

  files:
    image: filebrowser/filebrowser
    restart: always
    user: 1000:1000
    environment:
      - TZ
      - FB_PORT=8080
      - FB_NOAUTH=true
    volumes:
      - $DATA_PATH:/srv
      - $SERVER_PATH/filebrowser/database.db:/database.db
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.middlewares=auth@file
      - traefik.http.routers.filebrowser.entrypoints=websecure
      - traefik.http.services.filebrowser.loadbalancer.server.port=8080

  homeassistant:
    image: homeassistant/home-assistant:stable
    restart: always
    network_mode: host
    environment:
      - TZ
    volumes:
      - $SERVER_PATH/homeassistant:/config

  minecraft:
    image: itzg/minecraft-server
    restart: always
    ports:
      - "25565:25565"
    environment:
      - TZ
      - EULA=TRUE
      - MEMORY=3G
      - VERSION=1.16.3
      - TYPE=FABRIC
    volumes:
      - $SERVER_PATH/minecraft:/data
      - $REPO_PATH/minecraft/ops.json:/data/ops.json
      - $REPO_PATH/minecraft/whitelist.json:/data/whitelist.json

  minecraft2:
    image: itzg/minecraft-server
    restart: always
    ports:
      - "25566:25565"
    environment:
      - TZ
      - EULA=TRUE
      - MEMORY=3G
      - VERSION=1.13.2
    volumes:
      - $SERVER_PATH/minecraft2:/data
      - $REPO_PATH/minecraft/ops.json:/data/ops.json
      - $REPO_PATH/minecraft/whitelist.json:/data/whitelist.json

  plex:
    image: plexinc/pms-docker
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
    ports:
      - "32400:32400"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ
      - PLEX_CLAIM
      - ADVERTISE_IP=https://plex.$URL
    volumes:
      - $SERVER_PATH/plex/config:/config
      - $DATA_PATH/plex:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.services.plex.loadbalancer.server.port=32400

  portainer:
    image: portainer/portainer
    restart: always
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock --no-auth
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.middlewares=auth@file
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000

  static:
    image: nginx
    restart: always
    environment:
      - TZ
    volumes:
      - $REPO_PATH/nginx:/usr/share/nginx/html
      - $SERVER_PATH/minecraft2/world/resources.zip:/usr/share/nginx/html/resources.zip
    labels:
      - traefik.enable=true
      - traefik.http.routers.static.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.static.priority=1
      - traefik.http.routers.static.entrypoints=websecure
      - traefik.http.services.static.loadbalancer.server.port=80

  torrent:
    image: markusmcnugen/qbittorrentvpn
    restart: always
    privileged: true
    environment:
      - TZ
      - VPN_USERNAME
      - VPN_PASSWORD
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,8.8.8.8
      - PUID=1000
      - PGID=1000
    volumes:
      - $SERVER_PATH/qbittorrent/config:/config
      - $DATA_PATH/qbittorrent:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.middlewares=auth@file
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

# Migrated

  auth:
    image: thomseddon/traefik-forward-auth:2
    restart: always
    environment:
      - TZ
      - SECRET=$OAUTH_SECRET
      - PROVIDERS_GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET
      - AUTH_HOST=auth.$URL
      - COOKIE_DOMAIN=$URL
      - WHITELIST=$EMAIL
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.middlewares=auth@file
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.services.auth.loadbalancer.server.port=4181

  traefik:
    image: traefik:2.2.5
    restart: always
    ports:
      - "8080:80"
      - "4433:443"
    environment:
      - TZ
      - DUCKDNS_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $REPO_PATH/traefik/traefik.yml:/etc/traefik/traefik.yml
      - $REPO_PATH/traefik/config:/config
      - $SERVER_PATH/acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.middlewares=auth@file
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
