api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    # http:
    #   tls:
    #     certResolver: letsencrypt
    #     domains:
    #       - main: mchill.duckdns.org
    #         sans:
    #           - "*.mchill.duckdns.org"

providers:
  docker:
    exposedbydefault: false
  file:
    directory: /config
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: matthewchill7@gmail.com
      dnsChallenge:
        provider: duckdns

accessLog: {}
