apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.246
spec:
  type: LoadBalancer
  ports:
    - name: plex
      port: 32400
      targetPort: plex
    - name: gdm-1
      port: 32410
      targetPort: gdm-1
      protocol: UDP
    - name: gdm-2
      port: 32412
      targetPort: gdm-2
      protocol: UDP
    - name: gdm-3
      port: 32413
      targetPort: gdm-3
      protocol: UDP
    - name: gdm-4
      port: 32414
      targetPort: gdm-4
      protocol: UDP
