kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:version-3.0.2.4552@sha256:d3f735c5f89b897ac986768b112e1e61b2875e39cd05465bb3d79c3399f725b1
          ports:
            - name: radarr
              containerPort: 7878
          env:
            - name: TZ
              value: America/New_York
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: radarr
            - name: media
              mountPath: /movies
              subPath: Movies
            - name: data
              mountPath: /data
              subPath: transmission
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
