apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tautulli
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("tautulli.mchill.io")
      kind: Rule
      services:
        - name: tautulli
          port: 8181
