apiVersion: v1
kind: Service
metadata:
  name: tautulli
  annotations:
    metallb.universe.tf/allow-shared-ip: external
spec:
  type: LoadBalancer
  ports:
    - name: tautulli
      port: 8181
      targetPort: tautulli
