apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: homer
          image: b4bz/homer:21.03.2@sha256:0d7d7a054b19007293998fadba2f098e47d620f5d06fefb2ea853147bab61f1d
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TZ
              value: America/New_York
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
          volumeMounts:
            - name: server
              mountPath: /www/assets
              subPath: homer
            - name: homer
              mountPath: /www/assets/config.yml
              subPath: config.yaml
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: homer
          configMap:
            name: homer
