apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("mchill.io")
      kind: Rule
      services:
        - name: homer
          port: 8080
