global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: traefik
    static_configs:
      - targets:
        - traefik:8080

  - job_name: node
    static_configs:
      - targets:
        - nodeexporter:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
