apiVersion: v1
kind: Service
metadata:
  name: minecraft-mattcraft
  annotations:
    metallb.universe.tf/allow-shared-ip: external
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
