http:
  middlewares:
    auth:
      chain:
        middlewares:
          - auth-error
          - forward-auth
    forward-auth:
      forwardAuth:
        address: http://auth:4181
        trustForwardHeader: true
        authResponseHeaders:
          - X-Forwarded-User
    auth-error:
      errors:
        status:
          - 401
        service: static@docker
        query: /401.html
  routers:
    staging-websecure:
      rule: HostRegexp("staging.mchill.duckdns.org", "{subdomain:[a-z0-9]+}.staging.mchill.duckdns.org")
      service: staging-websecure
      entryPoints:
        - websecure
  services:
    staging-websecure:
      loadBalancer:
        servers:
          - url: https://192.168.86.149:8443
