apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns
  namespace: server
spec:
  encryptedData:
    config.json: AgAKpN5Bt0FruxzkjJqYnOaoxWQYb31L9/IRNpYAYKcVV1xOUJWdRIVVeoqmD2ycD/hJEowpd1JyZ1V3gQyoc7RYt4M0VE9kQzUeC9a8QibverfNEjAdMe0pIAm8VqJCbyU/QDSVkkMpFARDgTqfDSE8KKYUJrtOnanzKNqND+oykqdrSaMkF17U3Y3iq97xkCpdoEkFm4N1x9irKYgv2kePl/XX1/sBHCvlOU7WsmXSyYKfEaa3FzyNmjnR2F8YdEWaCtuVBNwal1TytmVBaO7NrIaVCzabLKIL8/gnLlWDQaoZJ+ehBed/wuxKZTngS/OD2mYp8gcD73hxj8TLm3duiWNpM0WCy6TZJZA0T1E4yNVbDTopuk8BHzV4BdnC5vCjGMiEKRmBBf6Zfg6+iz38A7qiMElDsGfIGAX4eQ7vQHraUJ7TKYnNTFCtucNhlyP3h9HwcjnxsA5ZMn1SLuWn6xlwZYYmWRgrn920p/SVGPzFTzjtKBHvDVMzH+wABb9OXrz0UZGUGgNMwHUDWcZRuo9dTI1RW9z1bLCrf0jUYCRiEgZhiajyjK9d1V5ezxsG/zwwMts+gijcokKkL+uLYeX2jcRVRki81WhlfUbmFymdjW/GD9n9hMbKrY+RjIHo9krZVOSGJkl+774G4nxiNHwAZv0VaZhDOh7f2ZxjPKOtO6TiXUhmrNae2JgaG/hXlImxHOFRicdCHRvPPLzYXwjGWlO4ItPm9coByvKfaJxc1RDPmK4OKXOmblj7YBwEzpmfUyy6nOTZrFyuJEEZGVa+Wzm8Ns1eUuetDYdfM3YoIosVvQLnWslSmKLK19G/PV8txFSsIcHKrVvrHw6OE1YnQZ2R3d99nyLwCqnrVfIh9JilpU8Fnzp3OkdIULmtZI2qDLwnVOCqHXPA87UO1NkkmqqCmJT/iGzNWCDnZfqVzSz0u0Lr+zbUBV5A0FRH5Q6t5oLP8NIn/vntbfDQEaBiBXDSeclxoczB94OON2NKiWpVU0wwzyKBZaczZwWhsTa6VGlSfmbbIKVk+jAOfyNJ/suh6HWv/UxNj3X2xJ0wruN8UTNnAwTTFWGNSVwSITrpmD4CEVGPFmS8K4FWSxIGAtrP/VqHx++9czSiHtLZW/seUFxZNQmRejXCFNVJTeL5zxbXA8T+6pHxF/mklT7khGiEuaDgS8fobA8MeHTmapgODCt2KwYyglEjuFLDBMYm+lmBADmHi9Y3EDsXRJRSlDoOWee55/3zNU7AXAanfYLRUROmlRy4sP2L8njL4foc5jOzNXTyqm+IxZxu8MQglg9c4mSNTXxzvliGD/0psJhxthmiqBYZhoKINYqwU63nsDjNlM3pV2aXcauQaqGcbcduBsfHEjS4xW7PAsor0Rsm7yRoip0nKhIWdoWg8fPOY0GF6+vPV+6/+OFl/FsqQhUQsF6EmiRDxNU/rb/RnWt6NMKro/M8ESP0bsnl1dn4UxIODPYINHSzdt22TvYqsLYWnDaM8EnoDpnhBxwEuEr6p3dsFbpfVSINMO2f75W//Tbp0SRRwqSanD9SoRKvuBZBQpm1zIZdGTDs04LoyltkB1qB5TXv4zur7NTqxIhS04s32CZS6MWh0SPBACDW0nX+PjUpUXDiXt8+T+KawfLXfAAAPnsrIxBzUBmK1QA9aZ6PPJ0pO/VXhbylO8K6BzpjTt8gBPE5Q3u3Zg==
  template:
    metadata:
      creationTimestamp: null
      name: ddns
      namespace: server
    type: Opaque

