kind: Deployment
apiVersion: apps/v1
metadata:
  name: errors
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: errors
          image: nginx:1.19.10@sha256:75a55d33ecc73c2a242450a9f1cc858499d468f077ea942867e662c247b5e412
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: errors
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: errors
              mountPath: /usr/share/nginx/html/401.html
              subPath: 401.html
      volumes:
        - name: errors
          configMap:
            name: errors
