apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-hogwarts
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: minecraft-hogwarts
          image: itzg/minecraft-server:2021.6.0@sha256:2cbb224858f4c1542e7d281995815555c8f64304a0fb3170c6a24b26b9d5ea78
          ports:
            - name: minecraft
              containerPort: 25565
          env:
            - name: TZ
              value: America/New_York
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: 2500M
            - name: VERSION
              value: 1.16.3
          volumeMounts:
            - name: server
              mountPath: /data
              subPath: minecraft-hogwarts
            - name: minecraft-hogwarts
              mountPath: /data/ops.json
              subPath: ops.json
            - name: minecraft-hogwarts
              mountPath: /data/whitelist.json
              subPath: whitelist.json
          resources:
            limits:
              cpu: 0.6
              memory: 3Gi
            requests:
              cpu: 0.3
              memory: 3Gi
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: minecraft-hogwarts
          configMap:
            name: minecraft-hogwarts
