apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mchill-duckdns-org
  namespace: server
spec:
  commonName: mchill.duckdns.org
  secretName: mchill-duckdns-org-tls
  dnsNames:
    - mchill.duckdns.org
    - "*.mchill.duckdns.org"
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
