apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mchill-io
  namespace: server
spec:
  commonName: mchill.io
  secretName: mchill-io-tls
  dnsNames:
    - mchill.io
    - "*.mchill.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
