resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml
  - https://raw.githubusercontent.com/snowdrop/godaddy-webhook/0dd48e5a1e47ab8f3f9f3d8d89d0481395ef83b4/deploy/webhook-all.yml
  - certificate.yaml
  - cluster-issuer.yaml
  - sealed-secret-godaddy.yaml
  - sealed-secret-duckdns.yaml
helmChartInflationGenerator:
  - chartName: cert-manager-webhook-duckdns
    chartVersion: v1.2.2
    chartRepoUrl: https://ebrianne.github.io/helm-charts
    releaseName: cert-manager-webhook-duckdns
    releaseNamespace: cert-manager
    values: values.yaml
patchesJson6902:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-webhook-duckdns
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Service
      name: cert-manager-webhook-duckdns
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Secret
      name: cert-manager-webhook-duckdns
