apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: godaddy-api-key
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBu2hTl9/X6ySMLMUh8fuwxVOrd8GWrUlUdLF5E52c9IVrmxUxo0TIw4NbJYAK2YXr//K8gdSsFdGSPkL66uLlR8WuBoDtuctqZjndg/s2R2eVn/AtMKnVeZOyMv7ylwnsWThZTmbuY3CxGeWVsu6OeLTLCW2G7tBsuU4SF90P26J7iWQ9la1NFb2JfMF/pCmLn9GoTF3RmRC/wHZ/0kB07NwPKFKd3S2jAgr/2ZT7I3VrU3McIPa9j9W5Ri7poOK6UzgYywTiMEIkBuNcFpF3VRS7wsXSZuxp8+1MrExBFGiuYpWFLoQ18rT5e/PIdhElPRWlwkAt1PeJ4hUB7UcWC36ERqIz0pcfhCYZVFGhh3Xt3/lrRoE7r8Qbp9OEKSbCjmDdQkqyOAubKR1sgzC3aKoJuApR0TK31ZWHq6LCPDuj3GyNXopCgLzQLiuYNrbebPrcndRaLzM4jrU+MOqC925iXvNf3SALw9napi5oee4/nU42JxrwETYhpeY3GE+BDiZ9plqsRYQXpuFjbwvKxdwRjUKHf6nR9oyHoM6Yjoz2wPVSBBca1PUcRJmHozQksMjSfU7MGbavz27t/27Q7mrIPZDgSvypALj4Wty6XWMm4c4uIqyQ9IrNis9LM8Vnge4ZJCnsdNyS/QXSJaEYmRRdYWZat+Qb1Jyrxb8kqi+Ztr9uOB6IK3mF12qjt7IyUOyaUa+9cruA+kxmilSL1PNqXXZqmhNxsSojM+4vBi6CbU09toKOvqJ0U++cbv42Cji5VD7vK558b
  template:
    metadata:
      creationTimestamp: null
      name: godaddy-api-key
      namespace: cert-manager
    type: Opaque

