apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: godaddy-api-key
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCZVwqVnix1HVI7YEWzrzaQBZ7Rd6+1ruruBHWaeG8hWxuESmdLwVvDRO9LieELx2jxV7N4NCT7xq9RRFnXKYVzAJVxUNRWKQsFbVFo3/saeYa6nmK1LzL/5TRTJOFEkPrIOmr5bjDqQamkMkdGPQJt4ifIYiqdSnJV6ild5lQldMatBlkN7BEi3c46GLW/zT+PlRnFAjphC0Og4syuyv1L3gbjm4uTcdzQofPpjcti8BtjhAxwJnxXMoKnEqqAZAJPvDX1nij1URo32qUVTMczIzXSt1DDZDnMxYPBkojRFbsaM1LcL3oQ7BwtfKUCCii6FFO50Xov6de+UhmupITvpmF0b2aMJEUU+0q3PeQKwlYJdc3oEENo3G9OvZoDxnXkLRc2lsHt0QGniBFLJHAg5qudYi4njBgPjRrQDUiPsnYIZPIqDYx4FdLlHCQoN4HbHtY59rW9+ggjwf0ZwQXWy7YAP+WsLeK5bfdhL9fHidrPEc747az+QKHfZPt2B0ulSS5IdCOw45clA2DymV/QgFx2A5LsZP5Ygw/xQwWCo624w8MpzJ5xyT7Ba7cvGbTxHi5JUeEnO7nX5ezAmRTyut9Wj0XayzX8gEGE5WD38DWJzP7cT2AIY8AaY6NVKthC+InOfnJD9KHOAAw3N4iOUpRi3xvcyof7UOBhpAdMXYqz1STMCMBlppgohtaElEbQmvJtAZPUsGBOxTQQtkXdRjvXrfKIHdCHkVUwbocas1dXpMtuM3P5hFwytbNzWOivZVBEFFxAZVlo
  template:
    metadata:
      creationTimestamp: null
      name: godaddy-api-key
      namespace: cert-manager
    type: Opaque

