apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  encryptedData:
    token: AgB6XDyaLo7TokQ9ZAy7s1y8Qwy1i9W3UM5trq/ntCIWH+31A8n6btTf4jfvAgJ77FVRWjvDlw4MoRl4S1yh8uvkXFylZkqhVWkoaRGNQO6qrb2yNQ0a/t5gHIVS2WZOheXM+xs8slvwdbDzFik4YH7o/yam3WtkYpnQ25vGAOjbY1Ai+dtOt4WgPE9VLygBPI/kIcxzddQlDpfnxXZWG0EWT7+REL3J1rfbcaGBmTcWBanQVYS2cTs1mj4Kxbe8uVR0wGuW1PE4o0x9HLpgYz/AeMf3J4depiUq/YQmMd7Sk/jb6HQ0gN6u+r6vKZSI6MxMXU0e/Skh/xG2+rAuZsAqLwZHoSrD9kir/iVDtNKz2xiXQ1/EAl7Ch5m+sNz9f9cxujM8nhNE6DjUHoqJBgjwda16e+aA6JojKPEoxTuW78PgH+EOsgK1B0AsrufGM4Fo11+K95n7D2tfuzIwg89BHRyfhNXnFj8qocZoxUxg5/4/JsKw9AcfXxwACv6vKRkSL8RunLpBraFaugmZk7ag9Hq8jJNfD+vhVlLTCyN6dScqOIVbkXYcc7RlJen+J3+yNz2o7AJTjsQROvSDuHFfw80+i+d62MuvOFTZ1jUD5AcjzS42txibf6won4uheeGNvbmXGa338GLz65E9YjP8zbRTxXpSG8FECeT9lOe1b6H6VNtrsu53rjcugDMHdNXCRRaBldPioS+HlHX0iz9dPoglWSFjB78oVJ7Zsx74MUa301c=
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-duckdns
      namespace: cert-manager
    type: Opaque

