apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAg7kb3i/bMopNOxpvOCZIjRxYBZFazq8Z5z47nrW8K4ofv1PO9/RF/f4GbwD/T0VSSZhTGZ5rnm9MCmOUdLyow+4/DkbP64dXD7xNA4Sbx9f5lVYJP8PWMX0EyX0BYkwh0ubM6GErb8B2ELALHOx+3Wpxu/1MKFQFZRCsDea79/RtZQxmk4EKLoZsm1VpBqmXVokmxsBJnsDhVq7SFnMgGUthYr4lYXqb/Gbfxx+XYvzH0AfpazWqbyWZ33kGlyx1HXJyVeNfwipBAeBdSoatoRKq9AiTIgxwjwj3HxwcjR/wYWRAZpvA7jj19TA+3w4keTSaPD7hsg/XBE6ue9JzKBDnldwb4U5KVF/u6AhvFTs95cYZmaf4Tnx15qvh9cSN4yl5GgxbiA29uk5Qap6VWui8kFkWHRx1hnwjEaakqLJvAttPJn/bhM8F+tlvmQrqNnlp8crTXvCc/CfpoQo17Mtu86Imy6bWdSusKE7K9+oo+b9oWhOhNU3oSJaioucqJEj/OeF2bROlUQ6aTah8rzGbn2phcwIN8cqFiQwsQGxp1fcIswgLpO+FOmhePqqVwmi1EF0SbB/RRb/gh/V9pleUKF9A/qKc/FDJzqPgig4iFVYcCkUkM28oXmoc9eegLQbEMsuwsVmVy17Vj3P3t0lAqekbnpzynNg9BGA2IgVLKMK8XcTwzS4ag4Su6JluyNHBhuqicXPUnyzgRZZvWDsnSsAQeISAAfKaODzTCYMAaIic=
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-webhook-duckdns
      namespace: cert-manager
    type: Opaque

