apiVersion: v1
kind: Service
metadata:
  name: minecraft-hogwarts
  annotations:
    metallb.universe.tf/allow-shared-ip: external
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 25566
      targetPort: minecraft
