namespace: traefik
resources:
  - ingress.yaml
  - middleware.yaml
  - namespace.yaml
  - sealed-secret.yaml
  - service.yaml
  - tls-store.yaml
commonLabels:
  app: traefik
configMapGenerator:
  - name: traefik-forward-auth
    files:
      - traefik-forward-auth.ini
helmCharts:
  - name: traefik
    includeCRDs: true
    version: v10.19.4
    repo: https://helm.traefik.io/traefik
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
