apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - type: Container
      default:
        cpu: 0.05
        memory: 256Mi
      defaultRequest:
        cpu: 0.025
        memory: 128Mi
