apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - type: Container
      default:
        cpu: 0.2
        memory: 512Mi
      defaultRequest:
        cpu: 0.1
        memory: 256Mi
