apiVersion: v1
kind: PersistentVolume
metadata:
  name: server2
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: server
    name: server2
  hostPath:
    path: /server2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: server
    name: server
  hostPath:
    path: /server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: server
    name: data
  hostPath:
    path: /data
