apiVersion: v1
kind: PersistentVolume
metadata:
  name: server
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: server
    name: server
  hostPath:
    path: /server2
