kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1000Gi"
  storageClassName: "microk8s-hostpath"
