kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: microk8s-hostpath
  volumeName: server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: microk8s-hostpath
  volumeName: data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: microk8s-hostpath
  volumeName: media
