apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: server
spec:
  encryptedData:
    .dockerconfigjson: AgBRP6ZlO3f0k+xRZ3JC1l8fz0gN2NTomXYS0WOEqURpCzVsKvYa67DJ2BpY+ZUNAa+l3J4HaxBz/DBJO6K+Ch/tMVSzt6+lfxCa9kk2rPmyu+kRJbclw7E6vkVSN7KF9ZSdILBvfQaqzEXMeWdJGEVfPpm7fWWwqOy8i2LD6OFokTctCRuXBsMe7MH6w0kBYg11Rut8Qoypa5mRXEOZxKcg1L+asU6qYMRFcEa9XcFsL6IjNng3oWc+RElP7TJ0VGo/d0Jth64jqNoqEWhCVjWMpzXl63z7nxrd2Pe3KiXAY8RcyauloLagTGHTqsf7Ehx6lbe9qvfH4rZ5nr73lrA1y1eY8XlzLV/N5+WTxTP7zUZ4vk/jm9emW/pd9QlRK5Lh+eG41/8i3KqF2KFcetouOXXIyOuur4jKITr+z/yRvF3z9NXlp0pg0QT7KFhtFRqnpnXNT3Pvr6MxvEnVO/dUU8cjR/klr+Paq5VzLEyN8R1xVBLsgXJ+hSQrUUNtYLJmX7W4HMfgD/ms+QNadYloTN1Tlf9/waV2q9poCqaYKR5PaX/dsnRb2mmGd3QTGNsBM83FPpwnQyfbKav7K2kznvwJX5yDqEVLVbqrFr1PRtLLZf1JZnioT5TDgTDeHwB3LA7InpvUUdKRLCzJh9DaDRKauOH3fHmoFv/J+wpN39GQr1a7YuZ9HAdwm3Ee9N7kjSHiIHYqPGPoSmvJcypwUWJUXTV1wGA0POJLejF6d9Vi4OpMUyuhwfHtAD9hWiSKF3i7BBmtuMM03yy2c5mwbcJGJnhhqjNYpX+MgojtWSIhBjOV5tlF5hkjQHsDG3zcoJm8teohDzvLaaUAAcNDE1kxESdabZOFlT9B1hoKac3qzl11Wq5ZElj7DlBXVGXqC8S2UVWfduGjgBPrqv++XYzmtTa5X9A1nn30mL3k+ht51kXvWvTbDVM75ESZXuWKr0zwYGhn3rJzsxBU
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: server
    type: kubernetes.io/dockerconfigjson

