apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: server
spec:
  encryptedData:
    .dockerconfigjson: AgBw43mCiIzuGVdNgimyGEHyWvkhGflfwtg1evJHCj1dnEX1wD/pKxH6muog014JFTk7VjdP9QVVJ2WgQrZ4koQiFgadwMu/eDnUuvxLVUTc6FTO56AZMBmuSq4SbZzrduZF01HPFNFJWNW6blgzYOWWmYzInk553LN8Idv7nivljicVmhZlJSNqMC36xa/tqbt/RmitI2EPvdZyJqHFJ7hkgMajuQIkGBflfv9DxnOi6Bf5WZhlxq+abJkyk2Mw4eTH2MGbe2PKwygY/zdUe9FQlBbucOMhfKPa3bOLJpYW5/6Y6VzYmEPyVGlQMNME6bMiRiVjd0FqCZCrfK/I8VHopPQpPqs/tTmuvqJmSgY+mOvauolwH+oUgp4DH5RpI+C0LxGvsGdPDThmdk446aYwJl51JA4tT0ueBKcRck8zMCqNMZk0nUuzVvbl8jmUMUTEdslyQLRNTv2X9aEwrU1cFIOqSL/FOGttvfdJjyaTZEhsFRJrildu+tJkvVpDO53XOWuiPUz1Jha+8ZNioonS7Rxq7Zz+N1CONs3V0iogU3TDjDI98nNpjP75VlkHNHFHB4RtBK7I6BAcEd5Hoh6c9VMYaG1l7ToGAX0lq8+T8UFkPRjL+j3gY8FBG57KqdGcjHmUJcYk+qefTwGdES5zjh/PQMszmVaq+kdoO06SnIeJlbahpRLg02c8SAApSnCBvZDempdoXf+6qpgSMiypQBTF/Wbl5AbZS6gubblw4lXASR10xJvPVIpRGjiZiiWf01wHzLn2pDpnlrRkLnwKuoWxUWotAPfBHTENO2aQxJw55S4nS/WeYBNN1JKnaF+e1tVeiDhRpncFRtamcXvxy0ddkAgCm78XWMLa325OTeXVQZjbUbzLtH8RIqeJqis/PE8p+9LHpBnJjgtrjIf503yv4eCjCmTz5gGDCeWSLmouvCjrnPBnpzsILDP1cjpdEz64dB4gro//kGOj
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: server
    type: kubernetes.io/dockerconfigjson

