apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: server
spec:
  encryptedData:
    .dockerconfigjson: AgA/MasHfPlb2lRe9cq0QlbKvUn5u/L8OuuIOIW0xh2eu3pQs4NYLKqCsQOXv73huP79oSTwqwDJOCDXjUepCWkOoujae0dS6McFT086w/stes63NYVx/8EzBUU0SQXgc6mYq1jhk7AWP8r9yEjFM64XsVLa65PFtjruoWqthIPMcPhOzbWixktsos+ETugoHLFlyCNoSIIcCmzSsb6PDx3UepUgqUjHug2FXn4nqzpT7YzBCL2yKlARrlUXV1BP8dNbBLMim2F2CXCzM8cnSdqvr+k8/FF3DaoGrpOjz8tYLu/nFOYeR3LEUfcic+0sFEvLoTpkVGBX1chRFmF8d/qcy7r0KXGPlu11BtJ10eSL8KCKiJussR6ACxW0oq0qiKt1CgQo0uz7k1dabFmn4gSV0Uc99IlKFP8ova429i5yoGywyv43vQHw0ivQWCRDEP5JXYlstqPdWu8cuHgpPxtjEqx8TA22QGBSDAtkx86JD6+oq7gwjAyAclT3qE62kAwYb2TD6oeWuKDKAEcjmDgKAftNO/X+SJrYUHJKaOcdwuFL8Fsy4iEA3D4afJWV+Moc+CfR4s74LjURMnxxI+sVtkbvJx/MDlbbxrbYdYVo1PSDkP/h7PKxG5RxU2RkMGzNhwILdQ0MMWShRALO9RKTXVk4kQCgptTvvmqxj36U2W8abIGWCw0bdkkW50J/ucUDDFCYutGa7kuR1Co1glPvwGcIJQSwrHuKBrku+WO8XTdYUC3pSwsieiXPXzWHTUzPRd0Ei6SXFPGJxe9qDz3HBXz8C+t66I0pV69e+AguIAFwE9AD3pCYujixjdbF63wzCLHrv5Oeg3VOFAq5rUalR2oZPCKPayOrFmcdcYJHhBI4zA4O7L1J6HfF/NasDxFeFlFDedmMLhEgULZ60UgOTji5DB5B4m2J+ploUHlw/qGitXzVK9cpOpMl2K1ns6ZKQUlRhoY0jmnNUYDz
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: server
    type: kubernetes.io/dockerconfigjson

