kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: transmission
          image: haugene/transmission-openvpn:3.6@sha256:56a7c4d9c47bd635576a6bca951cecf2b35aae39d490e8dec01d678e1316e92f
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: http
              containerPort: 9091
          env:
            - name: TZ
              value: America/New_York
            - name: OPENVPN_PROVIDER
              value: MULLVAD
            - name: OPENVPN_CONFIG
              value: us_all
            - name: TRANSMISSION_PEER_PORT
              value: "16724"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: LOCAL_NETWORK
              value: 10.0.0.0/8
          envFrom:
            - secretRef:
                name: transmission
          volumeMounts:
            - name: server
              mountPath: /data/transmission-home
              subPath: transmission
            - name: media
              mountPath: /data
              subPath: Transmission
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.25
              memory: 512Mi
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: media
          persistentVolumeClaim:
            claimName: media
