apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: transmission-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("transmission.mchill.io")
      kind: Rule
      services:
        - name: transmission
          port: 9091
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: transmission-internal
  annotations:
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("transmission.mchill.lan")
      kind: Rule
      services:
        - name: transmission
          port: 9091
