apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgAIFVJ8jcloiKms0XwaxDOx5i7SFdKJ8w95QqNHKvkWmE5JrwpnUjYKbqW4sIOYa6I6+eVbjEIZuk2FZbYqB5jDKRlWCpRsp3yJxcTVX6M5fWSpXoqS3vIkiKgVchVWN0pRNOoIqN09iHqriqKqL5yPasHOhcwE7YNJ9b4kysGPwWnEKcCzgo3oRNI9BayzZ7WmoCHfc4IMpElnm+M253E12hUoeEbfJrHy0VtKAGC/rFrzmR9fEOVH+s0RWY49SQLb+c9VLeA86EA+6Uneyd457AJEC+JjH6/ka2qkGTfv2s3nIs/q74mcTQH+deePP4/KbbQhuWLsorWFIamvmKiw7uyjakXazeDpkZqsGUB/1updoDh3bXf73hgWc9FMgvlQ0jaEMCP1sgDTxIqiTFbUc4Rg9H9NwqNfKmHwTfSfPYoXBMOza1HUkL8rmaa3dGzpHopJU1OthMgnMT1kvb584c64aF4wh9g42nMynNqRrGQctigmslvfrktlQFT3tX+pUC3pQp8j011AQiTTtKwdkOHU1X00ptutgl95murxQ4lmgEl5hkIUG5B0nhhnH0TWwN6crNsj7F+zebBxiqwrw9bySLzNMEe63h13/9TnAybPoZ6ePjhaQc/Q+OpDOJPXa5ZRZ8j/gk3Z5qQjbPlXSDDDNB06SsX87DDoIMjbTBQzAQ2sn2d4xNp0cJzuwdurtlrpAZ6vN0tL4Ixr7rFJ
    OPENVPN_USERNAME: AgDOOni3xzy+rI37P/cRKaE0DkAgKDwhAIOtM7Edq9Kinqt0at7mUwcqduIShjsxdDfHUVFp4DfOQF1w6CIOx+qNhm8fU+3Pb7pruDhw5r1z7PZeleBTyuna2kQF9RSoDDvIHpb+mNXWFwdEKmo+NwetXfpBu8vMQTQq0jwBWQ7z0O1WTBKeHuOdFM9ONhcHZFLjomStJFIL4eRiT5ZVMTOrJc7wfn7z4xiVH1VAlhbHBINvijXdJJ9ln2hJe/cm94YAF/Zu9ISUb/FscRL4K0YM5+9N/oU1yTzq3KUm7xX78M6+AnEp9sN9m4ZlRdN0o8tDwX5NVYbfo/gVxKqkzINfJLJqJTVXkjWXlapVuqp1eZq50SWINO7p46U46p+Jvf7X39ACHgHhcabkgmI8Oxc6KQoK9rU4D4NK1IXJWdVI3pvdq7OJyARLDiTBpTVd1kuIS6Lv1BIAZDPBcYHr79tNgwH/D6yl55G4zIHtu8FCOzhpZGDI4Xmec7B7nAMdWwgO2UJfi9QkeXej6P92J68snGCiLcvjukgaXJ/Ht5UKNagkgMb7MnywjBTKbomUh6Ei59qdx48rkJl5BkCLB+h3Dd3NchbB8geNhQZD26L1YdZmavEpDc/UUVe0RNfjacmZLUIRtMHsNXzMmUQvCmwXLgC64XOjdzyO9zM4jE9w8X5w4NGkBpC76bQfxWGRhtkDJIcay1yH1q3L96ZsoNcK
  template:
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: server
    type: Opaque

