apiVersion: batch/v1
kind: Job
metadata:
  name: restore
  namespace: server
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: restore
        image: alpine:3.13.5
        securityContext:
          privileged: true
        args:
          - /bin/sh
          - -cex
          - |
            apk add rsync
            mkdir /mnt/old
            mount -o ro -t ext4 /var/openebs/old/volume-head-000.img /mnt/old
            cp -rp /mnt/old/. /mnt/new/
            umount /mnt/old
        env:
          - name: TZ
            value: America/New_York
        volumeMounts:
          - name: old
            mountPath: /var/openebs/old
            subPath: $OLD_VOLUME_NAME
          - name: new
            mountPath: /mnt/new
      volumes:
        - name: old
          hostPath:
            path: /var/openebs
        - name: new
          persistentVolumeClaim:
            claimName: server
