apiVersion: v1
kind: Endpoints
metadata:
  name: router
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - name: https
        port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: access-point
subsets:
  - addresses:
      - ip: 192.168.1.240
    ports:
      - name: http
        port: 80
