apiVersion: v1
kind: Service
metadata:
  name: jitsi
spec:
  type: ClusterIP
  ports:
    - name: jitsi
      port: 80
      targetPort: jitsi
---
apiVersion: v1
kind: Service
metadata:
  name: jvb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.242
spec:
  type: LoadBalancer
  ports:
    - name: jvb
      port: 10000
      targetPort: jvb
      protocol: UDP
