apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
spec:
  encryptedData:
    GF_SMTP_PASSWORD: AgBVfshQRUYAPObekmI2HQ74exyF0BF4Powtnu5GRQwEW0SHPBZbL2IvYkxd+zlwXamyEuFVYQ19elL3sCc3CWwpvvVlxBui26+XqEOHUOTVxZGFBlf+hnLnHojHR8s2BitSzj1DD+3E+2JhCJ/xJUjYjQF0UBeR9TZXI6YwZ8Xiec8qwUnTl5HnWa8YFddHBiWxScrFxhWYKa+JVSlzPP2uYYNlfKM4AJAJ0LHzLSoIpBGhpOcX1GKpxDDWD9Ru4uLjRjEcf1Zf+znhBydpZeFsJ+OvY455Cx3AuO6qmvXjpOZSfdKRW75JtFjbSKUrYpki43hLGLAD5olD3Kcz9MM7fWvae/dgq/wTYmkSst8LK+0kp0RQssZZsXu3Xl8YEWhXZm4VGR9JWYviX9vUK+QP9IwfnSUkYq+d0zgy+575bTo1kK9Ulqznea/Ansy0ApjKpz+s3Kxg0WiyylEIqGHrHposVjt6N2VKM4rTkzugJ3vZRsMxAm1zSJ5FNCuvnhGSkqDBRHOP6XbiTYr7Rf9o79XFbOC0tLU0zLk/wocvVcibIOhr62vwqsSd3z3Rj7jtxlj57JMJmkB7L1ua0bx+vzhuzvcekAdHsrz9NUH/aAzdNkzIme8jQ/paDLDoOFGq94zVcMQmoOTcVWdsmUKcaE63ONd3WcaYbhapM81G8h6SItF3rGj4Eimi2ULV8J6phYf8+N73n4VuH5gr5tLg
