kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:1.22.1.4228-724c56e62
          ports:
            - name: plex
              containerPort: 32400
            - name: gdm-1
              containerPort: 32410
              protocol: UDP
            - name: gdm-2
              containerPort: 32412
              protocol: UDP
            - name: gdm-3
              containerPort: 32413
              protocol: UDP
            - name: gdm-4
              containerPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: America/New_York
            - name: ADVERTISE_IP
              value: http://192.168.86.149:32400
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: plex
            - name: media
              mountPath: /data
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: media
          persistentVolumeClaim:
            claimName: media
