apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  config.yaml: |
    http:
      middlewares:
        auth:
          chain:
            middlewares:
              - forward-auth
        forward-auth:
          forwardAuth:
            address: http://traefik-forward-auth:4181
            trustForwardHeader: true
            authResponseHeaders:
              - X-Forwarded-User
      routers:
        traefik:
          rule: Host("traefik.staging.mchill.duckdns.org")
          service: api@internal
          entryPoints:
            - websecure
