apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("traefik.mchill.io")
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    - match: Host("auth.mchill.io")
      kind: Rule
      services:
        - name: traefik-internal
          port: 4181
