namespace: kube-system
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - config-map.yaml
  - deployment.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - service.yaml
  - service-account.yaml
commonLabels:
  app: traefik
