apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - deployment.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service-account.yaml
  - config-map.yaml
  - service.yaml
  - ingress.yaml
  - sealedsecret.yaml
commonLabels:
  app: traefik
