namespace: server
resources:
  - ingress.yaml
  - middleware.yaml
  - sealed-secret.yaml
  - service.yaml
generators:
  - chart-inflator.yaml
commonLabels:
  app: traefik
configMapGenerator:
- name: traefik-forward-auth
  files:
    - traefik-forward-auth.ini
