namespace: server
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - crd.yaml
  - deployment.yaml
  - ingress.yaml
  - middleware.yaml
  - sealed-secret.yaml
  - service.yaml
  - service-account.yaml
commonLabels:
  app: traefik
