apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: http
      port: 30080
      nodePort: 30080
    - name: https
      port: 30443
      nodePort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik
  ports:
    - port: 4181
