apiVersion: v1
kind: Service
metadata:
  name: traefik-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
    - name: https
      port: 443
      nodePort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8080
    - name: forward-auth
      port: 4181
