image:
  tag: v2.3
deployment:
  additionalContainers:
    - name: traefik-forward-auth
      image: thomseddon/traefik-forward-auth:2
      ports:
        - name: auth
          containerPort: 4181
      env:
        - name: CONFIG
          value: /config
        - name: COOKIE_DOMAIN
          value: mchill.duckdns.org
        - name: AUTH_HOST
          value: auth.mchill.duckdns.org
        - name: WHITELIST
          value: matthewchill7@gmail.com
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: SECRET
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_ID
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik
              key: PROVIDERS_GOOGLE_CLIENT_SECRET
      volumeMounts:
        - name: traefik-forward-auth
          mountPath: /config
          subPath: traefik-forward-auth.ini
  additionalVolumes:
    - name: traefik-forward-auth
      configMap:
        name: traefik-forward-auth
ingressRoute:
  dashboard:
    enabled: false
logs:
  access:
    enabled: true
globalArguments: []
additionalArguments:
  - --pilot.token=$(PILOT_TOKEN)
  - --metrics.prometheus
  - --tracing.jaeger.samplingServerURL=http://jaegertracing-agent:5778/sampling
  - --tracing.jaeger.localAgentHostPort=jaegertracing-agent:6831
  - --entrypoints.websecure.http.middlewares=server-auth@kubernetescrd
  - --certificatesresolvers.letsencrypt.acme.email=matthewchill7@gmail.com
  - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns
  - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
env:
  - name: PILOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik
        key: PILOT_TOKEN
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik
        key: DUCKDNS_TOKEN
ports:
  web:
    port: 8000
    nodePort: 8000
    redirectTo: websecure
  websecure:
    port: 8443
    nodePort: 8443
    tls:
      enabled: true
      certResolver: letsencrypt
      domains:
        - main: mchill.duckdns.org
          sans:
            - "*.mchill.duckdns.org"
service:
  type: NodePort
persistence:
  enabled: true
  existingClaim: server2
  subPath: traefik
