apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  annotations:
    metallb.universe.tf/allow-shared-ip: external
    metallb.universe.tf/loadBalancerIPs: 192.168.1.250
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8123
