apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:stable
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8123
          env:
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: server
              mountPath: /config
              subPath: homeassistant
            - name: wyzehub
              mountPath: /dev/wyzesense
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
        - name: wyzehub
          hostPath:
            path: /dev/wyzesense
