apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jitsi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("jitsi.staging.mchill.duckdns.org")
      kind: Rule
      services:
        - name: jitsi
          port: 80
