apiVersion: v1
kind: Service
metadata:
  name: jitsi
spec:
  type: ClusterIP
  ports:
    - name: jitsi
      port: 80
      targetPort: jitsi
---
apiVersion: v1
kind: Service
metadata:
  name: jvb
spec:
  type: NodePort
  ports:
    - name: jvb
      port: 10000
      targetPort: jvb
      nodePort: 10000
      protocol: UDP
