apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBgv1DuZP5UOY/1XRPgTyFtHfUwsZBgJgwTuwpHAz/JJvLxY03Acq8SzIwGp3TWubatjaPKo/YsMg9ez6TJw4YnfZik4BkNIK2zuu4c5xOUnBenwZn5Db/4ICTZf1VVJsI97gv+QDMiveH+Oh0NUulY72KP3OhzHJBD8nHEqW1E45ZIXQN/VroHQIjrt/+esgfnNQOfo1DAYr6OZ2NjoaQYQLmFeWa4OEhQYv6e9mcQtTPAmCHnBlPkOniuotqqsaruzKzEGXb3iR7o4F1ZUUW6r+vO1jRJTH2HYWGRxL3p/5axKgEosy2t0/MDGfftzCMmOImz4KpEwf9kf/2b0IkDDaHwKSQlGKLoEtETm+yXs1VFcriPafCIIak0Dm/DrOPi7PTIsM34X9+8hhFGryFXzX3Vy2gRqEM3XCe1SMQFrvoWIvUDAjGNK42f8nyd/tBJwC26n9BvhBk1MKUsVKfvYoLC2FYhUu+6B8BpG6kuH8R+Emiy0vGL8rB86SaHVERXTLBIE0QYOVaQuKvRNPpP2VWYIzv5A3IUldWKTyt1Q1Mamk7nWbMgcB8MSLfZGSjwz1QdkGq6bbLmj1DpCRoRbjgiv+N6Idax41Hf7ngoPH0CGaSJ+TPHHMG2V5iAWodWx8W51Z4LwWzO0zA7wYklZjm3SplhFeMGFsI+VmWnh4P7HonDm8HNvh2U7o0YmL5zQuhqdU34YpqRQkwu43QFmILHbHARfUJiCJFZziTjYVI5JVABgGyYJDLRMgQj89yi03b3wCnPW93Er62a1fhXwW/6w6MOX4rEXbSa5AY2qimcE3V7yXlOqrFefDFiHq1WTTkk3dB4tZmNAN8LjoByXJ/Sg1gJYj8VhV/u4oE3+l6MWX1QOuQRhDYpola/G4u8bRVFb1ENHbmSwicHBKcTbuPThFAhr2sUAmWZuS5u
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque

