apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBIwecBEw/mkt5MsMcRtMn8mhrAKymlEwbWcVrYyY4JI/QLXzPidC7YYUiI0V07kvd2YgZ84igSPrRf4fAcLdTsaBYtge4FsOQNs8D4MeFnSEIKuJDJcwtlwv9hHabqmvPHRiZpvlvgTqCRkxyNBIhz1/5J1btUu9mFSb1J4oRY+pIVBaMnlHM3XnqV7EXnlGiiooT+VDonbGmGdONHRXtdxUK5Ovw9pDfU6lTGkohWy6YzEOjm3EuP2lfLBMVrDnaD64MbgegQ/A26Ic5HY3S6huNBYjudIaw/aTBKPMtsFUhgiWGxC+g5OIacH/SFbQZtlnrs5qymGtonbrR5o2oxxoeVbMyVy0wjPgcfilx4T0o3FRtgTESEU3ynVFpEPzSZo/u8/TLsylvB5eM4KqPnXrGGfKM2tp2jSjJgKMZHY6OeeN88boZswBRmUmmXuewxQTjOOQS7cugj72dhFZ0wq7TidOwGQQHrnSDIWF5ZWCWLv+xTMACeUdsoayfqfgQ02dKoS2wLW5z/lXTB7vgfHPiuSBJvThGI6R+OqUamMjDiOwddHIaRET9kwkeSjwhLImbi3ALfsCxBUkeVBl9d+0vvev7GReyYen6maNJ2r+HffQRbY71O9MQrABP9SLmJJ1K6Zb30rzYVEApxtmG3eSqitInhLNXsrGilDSbgClu8boZwYfvSyfLHpNT1FvNJyC69bNh1TAAEC2/+FkbVP9M/olB51O9iwT6LXJvrnyIsuaPGRhufuoOyhTQybaHwaseYgfb8y6No9U4XXTK0NZnCF+K4V5oSxHo4L/j3liOxGIUWdItBKvvQnvFAjEv78N6LIbkEXt+1/4ENRRQG4xJTnxTc0AVvQiUV94DKRFD/mhsBBnFcRzRIN1nTn2oTloDNp71qjBUv6aOJ6ilbQSsFCGB2I5BjXIMmyvPG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque

