apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgCzfV43AZY0BL0+nJ1Lis0clpZ4+KSJFUp36mZiCvoGaL++HCQEOfDxO4ww/x9BF1KoJaIpisujMvCeT9ncYSzGYGeeuKdIX2mtyA2totIP7Zeuv+++I+uwDqWv33GkeBEvE6Dnfkv0TnMxVrUcvmT/++tCTEou3olZKZwh9NU9gTBxAj8H1PD5K//nLazch5Zax3HBM1kXDLuRiG2jI9G81tOKh8vK1SweOyX73xDrgsKIbSvd+ay84c/zxq3U+fgDwQ3klXPzNvlkA5QipEGUdBvdDpOuLtRlZlq1VU/lc8VzXPqCH7bx85gzha9cFav4qwFJnqFD2h+tKUvZxANr3rbctjff0ycHeaQmvh9KhySInvZvgNtKAoMRlGnLqqVq98DhlOt2pBulhMn3VoPKtrH1/JMEV739HdLe+mgFJLaP4OXkrc6WbhkkOkoqqaESG1pIjH92IqahsJi4hmivobAjqwbIpNs+BNhjGw99Jfy0VGj475RParABQ+YdEXC0TAn0XglCqozRfWJgwDqiA46qi7/kbeP33klxVJK97G8pTCIDGVSiZz3b2I1yYW8j4vBv7eRP4XuCs6goPhSO5XP67qo0kRXAMN18UAYIGi1lrsjTWL0NUy1+2MInYGDpJ9iFsHqY+lSJ8wY+PymNMSG9a8f9qWBS6tjGr3dqxwxtcXAp/yRVQuJGKq/3pxUDzVIsauCNpRdD9jIXFKFyzzmoWCdHDp2gN0cUkIQ2HikXjXGUpKp+Gxdr0TKh0zlL26k3YHRdLva1LkKYBfTlyeCgVXo1jYPrg2oXoLhniJl9HfZTBLfkQ4J7PuJZ33rx4E2TN/Ei0OBIQ8N9wxzukzsw5l1i9D5WSp3GCwlFATeEel5Pj9GrKvqa/7NM3jVr8RMdBAZATMLcWaagKNW40zUhSVyeZvPipJ5gaf8K
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque

