apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgCLXeikfLi1qBGqIxZjjmsI0HQWZfJ9BkEjSqk/HxSakkd2r6vTVPTdk/jfQEDlOHG80f0Lhd6nBN6oGB6sSPJnb2IMQaCxN/rFRn7LSU9gQJkUhs0ERKhYRLNQA2nDP+HJHhhAnSVC4N5AujUY0pmCg7yvmxnprxmjvk68E/LWwUyTOfp2eDpOw/nctvtfowaHVpbTVJRHJaFVttbttq5iLwQ0ecIzbeh5njW3gpQNjfHpqRRSY16qtOMJH7QTDogRvWuF2EFT/a99qAvwN7UOhRucoSyjbOt3dQlapJPa+guyV52LHcgE50zIvbgD3uUQtXOYPTVHLUfmIK3e0XOfehWgC53l+CPPyX9ho16W2Q6+0mXcTGobQVsbUdcyjtQGHg9qFzkEvyVvOGfbSMiDCrS6a35aHF8o2Tgo+zOsvGDw6au4yQQWeA6AOEZVikiOXWU6L2mMRB/TVqUY2cGa+hEHOIoKI7kORVDiuJcUfbcyzywAMo7l42l9+BzB8kDVCfdP5QTgqvHi5LhVrg9iA2QDPzw8ZwKb9oa5p6YDVjC9EOi3E4wzZEYMuaiXDk4l6GODWscsGVRkx2K3Oofl6CYVcTESFsIl4LHyP0DULlddz+RewR/kSR3VssgrvkUsxlk0FT4+itxNfvNzkrjIP/U/GLZIkV/Rjdzsha2DZ0lKtdc5wqJLUwYwQoywM7oxpyz0AVSHZU2BcdHEo5Htf+Ce+KA/Cp9X0t7Tlx9gd/YxZcSYr6UxpIQw0ZlQ5B+zfTdG/7UMpCQWpGlaEa42drjyPtjQv1rXZE5gxbZIuksGalMv4lfLUSHtqQk/o/IfGQjHh7JleC/+oJJF0E5BwzVuLIybnE4CsTnMfiO9OlVleyQoJm375l6kG6btHTdpK3rPrCpifpEfz+cIcaAUz0cTsCZbAcb3I0S0wTP+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque

