apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgDhwQ55YCDJmk3FmJTs2e5N2fPUBTFuI0wxZuG+UYmx7q4S0zxl7De9fpZ4dKHfvJTWpKIL3gh/x4ZFG9IHRWAZvZaAVOriv2cWxwC3zAdBYDCRwU3ueRVDALOJtZOab8iDsTpdbuBI25KlkAnEz3aS02p73DMVmFEIIEbeIcWiR1KVB0ovw20lYOrzWV+wl40tHVFpyIxV6PG/iYUAUHbwwg4ucovtAROgWNmcuGaIR6KSi90srPufRX2pCsukezYRA8dtYXgmCPPOhhwQ5nyLls1mSVG8JLM/WP8DGqDmNAgv5zD3V1nvPqVF4vpxf7ZbZIeEoMLvXFFqeiGrOGSH3K9FAiqye+aS1xibew5RDphMv+8OTT8EpqTsw2YUNbix9XUP3FrVdF6bFxpnx0ds2beP9x6CUtsCjmkNHrhiNg5jR4mPMAmqivPMfUBYCNrZM/92EqC8gfCL823W09NblOjKyoFWqEONuUAXupLbFG1AIl5MYoZTxlZSUQfTJyyf5Bv1mx7qHtSjhRA8LTdpoO6wayAGG89Mpe0+WVngaHNIzE+BWFCyk8S8G5bUKYUvqSm6WqPX0uIuXK+qscng3tmcBjn6OQXFSIWBfjtBlavOTAz7Gqz+5T6mQngFrR05lzetm8Mc5q46twJx4X4DJzzi2y5fJfNkeD7NXgiV0j7QdLLAMRq/0rggsVcOrgBKQEkGkqlTLe4UEHKPwp0NIj+/v8WayKMNc2ex1zbLnxK4T+NeKFWVHdpcT6gzNwr6zIR/SxOuVOyPrczPuwhBprO34UwFfw3CrgKsqSxTOupKWZsb8uM3+e4vB5+ssHu+etQ9rTCTIar28DlWB8vH64/LNSKHfikMOOdgr0uswH//3MKfimK4CJhxxI84Ft+LKaLpAUqEMBdfI5S1Ab3ugu+FFAydpTwOYA/yXqEK
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque

