apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: audiobookshelf
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("books.mchill.io")
      kind: Rule
      services:
        - name: audiobookshelf
          port: 80
