kind: Deployment
apiVersion: apps/v1
metadata:
  name: duckdns
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: duckdns
          image: linuxserver/duckdns
          env:
            - name: SUBDOMAINS
              value: mchill.duckdns.org
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: duckdns
                  key: TOKEN
