name: Home Server
on:
  push:
    branches:
      - master

jobs:
  dependencies:
    name: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/dashboard/package-lock.json') }}
          path: dashboard/node_modules/
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
        working-directory: dashboard

  test:
    name: test
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/dashboard/package-lock.json') }}
          path: dashboard/node_modules/
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm run test -- --watchAll=false --passWithNoTests
        working-directory: dashboard

  build:
    name: build
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/dashboard/package-lock.json') }}
          path: dashboard/node_modules/
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm run build
        working-directory: dashboard

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H mchill.duckdns.org >> ~/.ssh/known_hosts
      - name: Deploy server
        env:
          DOCKER_HOST: ssh://mchill@mchill.duckdns.org
          DUCKDNS_TOKEN: ${{ secrets.DUCKDNS_TOKEN }}
          PROVIDERS_GOOGLE_CLIENT_ID: ${{ secrets.PROVIDERS_GOOGLE_CLIENT_ID }}
          PROVIDERS_GOOGLE_CLIENT_SECRET: ${{ secrets.PROVIDERS_GOOGLE_CLIENT_SECRET }}
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          JICOFO_COMPONENT_SECRET: ${{ secrets.JICOFO_COMPONENT_SECRET }}
          JICOFO_AUTH_PASSWORD: ${{ secrets.JICOFO_AUTH_PASSWORD }}
          JVB_AUTH_PASSWORD: ${{ secrets.JVB_AUTH_PASSWORD }}
          PLEX_CLAIM: ${{ secrets.PLEX_CLAIM }}
        run: |
          ssh mchill@mchill.duckdns.org 'cd repos/home && git pull origin master --force'
          docker-compose pull
          docker-compose up -d
