apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mchill-io
  namespace: server
spec:
  commonName: mchill.io
  secretName: mchill-io-tls
  dnsNames:
    - mchill.io
    - "*.mchill.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mchill-duckdns-org
  namespace: server
spec:
  commonName: mchill.duckdns.org
  secretName: mchill-duckdns-org-tls
  dnsNames:
    - mchill.duckdns.org
    - "*.mchill.duckdns.org"
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
