resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml
  - certificate.yaml
  - cluster-issuer.yaml
  - sealed-secret.yaml
helmChartInflationGenerator:
  - chartName: cert-manager-webhook-duckdns
    chartVersion: v1.2.2
    chartRepoUrl: https://ebrianne.github.io/helm-charts
    releaseName: cert-manager-webhook-duckdns
    releaseNamespace: cert-manager
    values: values.yaml
patchesJson6902:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-webhook-duckdns
  - path: patch.yaml
    target:
      version: v1
      kind: Service
      name: cert-manager-webhook-duckdns
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Secret
      name: cert-manager-webhook-duckdns
