apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns
  namespace: cert-manager
spec:
  encryptedData:
    token: AgC1VviUUZSV32xXHo9r/1wvuz+1G4XA2RoGQDmPFolgQRrPKQoB2umPkHQ3AZtDepf7EYFkH0wvMwGUwXig/EkgUyOYkcxy7Btl4y6SvkAl5Rlw7k/PTaqtSl+4flC8UrLtWatDratzuuTu0PAGEi3sg2H4WF6DtuLA0U5mgDvkiQg4XCgpL5K+JDb8LC+aZZvc3gOoU3hKfdZXVE0ksY8fG637rII9/YWBHYfz4TSEE+Ljg4i3VKRxnhx5jaoTwU52RGBWg5TaSpiLnAh72l864C8vtlOa/0QR+vYRdsBCdaF96QvVb/87DXRr2BR7aaid5TtS/Vno+ug6BUbntwplOyaKGfiYKB0jWkkUSAIMFLJWBe3b8QnoAqM85FWkYRC8z1vPubwxeBMmGbqw6TSnF2OI4opMZp4lnifu2CW62MNux6gphOOWXqAtBow6Lzx6seS+OPfOfP3NcTa+t/+iqktC+e/7xiGW/30rkFoOE3kfeGKf5xYTYQps9TzNcdvIU6ohkx+TTyWLXn1sldJUa/lc6+4CzVaX5ST6JyGFT7n9VnKdeT7KCAPb8tj5h9qHuRzgNQutd3w67+W5lzVgFQmTi0dUikBbQ0lSsVsIknpDBJ8raDaQQ+ZfSU0sA4dIer3OLg8s6JkmzWh9Qo17W1XJxTJMPs4Pye/w/ReEoPJ2FndgzH0b3rbv1TvzWCGXJPAoNM7cdtwr2EpkhV+6yDBaCELcx2bSkENCbxb9IDO3Chw=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns
      namespace: cert-manager
    type: Opaque

