apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: godaddy
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCT+GXpHzP9PTwuJfiLk9Q+AYzeqEguNv5Nj8mtMO6pu2xfeGo/dJMWt+xY8fujUHm8jcLbv43Tg3WskSFyvV7yToz2S7Sd1zdO5KgNtaPcXGNDq0Lg0pTAWDJPybkyMVuiWv0vXclnsCS0B8L7zn/nLz6rVnAd5FbX1HssHbbG1Hd63Vfc7tYj3Eb8m8DUN4bOCpcdsQZpYicaGUiWc7QDACWyIv+GV6W8Hx+VHCUmIbzzUWtbZZI8lpCjCbuhl54FuoTzb6hbgdwe8xgpdMv/4isauqCnsJQKMzlF+gpMvKsWA6leJ9/rLrSkGONGCxuJzxzUjN74A30nrQy6eDXsNMFtEmXS7TYZgfBZ873T5ffADSV2OolfhX1Zd4BS5osFP4e+kdUV9lR08EKs29lHcMcWux/riGmr154EbP5WhPXGtFYa4Q0x/WlWnJeunWZyk7453NkyFvPVLpUCDd2PaaiMSp7gTRiyqnizzyt/T2PyqN/PDXu4/K9k7xqpTop0G2ZyWLtfluJh+cunFoFz+wOotKjenyNoU0Ncungdr5Xihb5lzZuFiZFR/h8T+WB3TA69X34b3vLMVkLQs2mCo60Spa9RqGR8+pbvw2WW0c2o+9IdJEumdlj0tC0/ZdazAETXB1JYztCVVLkGQT5XoJaf7MJ+HcPudi0XTotlFQuis7gCohamUlL0pasWtLpNK9TFVn1pT13s8s220DNX57OXuQ2QqhvH2/1uFCFG2zYSO9gwftlhONJVsb7qQRz2dHuv1QupZ604
  template:
    metadata:
      creationTimestamp: null
      name: godaddy
      namespace: cert-manager
    type: Opaque

