apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: godaddy
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBKr7UjAekbgO74lB3SVWVXuMUxMYWnzIktSgtbwYs9si99FTnVlj0cfpSQH9tIzBpZMQzQ6oGeX8SJD6HdYpcnSFPNe5s1vLUF6kREIOHDOUvRrhKklSKKu/mMs7qHdBSJ7zeAHGJscj2pkvNNmqjvvPfwMeuC9UdoC8k6fYNgnhse3dkEA6LISGoZBjc1f5e0WpbZEPGv4riGc3HHCgdZf1MEg8bC67ElHGyf5Nw9LCaqU+Y2kHApWHkAE2RdX8dKGkjCwtxAw/zHtPKN28kF804Ai0Phdb1OS/cX8PFTEcDnymwYI7mSiZayIgyAvQS4lnK+7FAlWX412lvV3FmoprmirRqnvK46UuWEzb3dPELmv/iYP1oC/GmgwwfmjCnq6g1j1aDBZm8CwW/QraMRh7TMesVNTjw86o1cseih93IjkATshlb90lrSa2Pops75w7WjLj+dWhUF0M/dm/AMNgvWiZy+PitZc/o6c+b9+KaYcFXJIEXRgyCPlr+SBYA1WS8fARZAoCopy9b74uLf9by8MrApi+sqPu6v21RCn0ZZ5rDgPUs2plp4wRnpCi2M7zOAzLaoIuSvy7s0XjX3/DDVzjVWcGAI7T/mpmewCHmtN2uOhLjkFqaY5R9cDqW+KxBtUDMY+uONngz9pYmiGqaBzwJobUpm3H1FgTmkSRO19WV/RTePgJNzN68ojtTLvq3/R8oRWhWjAvOl2+UJLVWK/4HoR6zLrv6uwoaQqCVJPumu7KEZ5p8QF9NTNzCn3u60DFOrZnxJ
  template:
    metadata:
      creationTimestamp: null
      name: godaddy
      namespace: cert-manager
    type: Opaque

