groupName: mchill.duckdns.org
secret:
  existingSecret: true
  existingSecretName: cert-manager-webhook-tokens
clusterIssuer:
  email: matthewchill7@gmail.com
  staging:
    create: false
  production:
    create: true
